apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-ngx-backup
spec:
  schedule: "00 21 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app.kubernetes.io/name: paperless-ngx-backup
        spec:
          serviceAccountName: paperless-ngx-backup
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: docker.io/rancher/kubectl:v1.34.5
              command:
                - kubectl
              args:
                - exec
                - deployment/homelab-virtual-office-paperless-ngx
                - --
                - /bin/bash
                - -c
                - |
                  rm /usr/src/paperless/export/*.zip;
                  document_exporter \
                    --zip \
                    --split-manifest \
                    --no-thumbnail \
                    --use-folder-prefix \
                    --use-filename-format \
                    --no-progress-bar \
                    ../export;
