apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-ngx-backup
spec:
  schedule: "45 23 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: paperless-ngx-backup
        spec:
          serviceAccountName: paperless-ngx-backup
          restartPolicy: OnFailure
          ttlSecondsAfterFinished: 86400
          containers:
            - name: backup
              image: docker.io/rancher/kubectl:v1.34.5
              command:
                - kubectl
              args:
                - exec
                - deployment/homelab-virtual-office-paperless-ngx
                - --
                - document_exporter
                - --zip
                - --split-manifest
                - --no-thumbnail
                - --use-folder-prefix
                - --use-filename-format
                - --no-progress-bar
                - ../export
