apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless-ngx-backup
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: paperless-ngx-backup
  egress:
    - toEntities:
        - kube-apiserver
