apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: jellyfin
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  ingress:
    - fromEntities:
        - ingress
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: api.themoviedb.org
        - matchName: image.tmdb.org
        - matchName: www.omdbapi.com
        - matchName: repo.jellyfin.org
        - matchPattern: "*.mirror.jellyfin.org"
        - matchName: manifest.intro-skipper.org
        - matchName: cdn.jsdelivr.net
        - matchName: github.com
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
