RELEASE_CHANNEL=experimental
RELEASE_VERSION=v1.4.1

gateway-api-crds.yaml:
	wget https://github.com/kubernetes-sigs/gateway-api/releases/download/${RELEASE_VERSION}/${RELEASE_CHANNEL}-install.yaml -O gateway-api-crds.yaml
