apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: uptime-kuma
spec:
  parentRefs:
    - name: default-gateway
      namespace: kube-system
  hostnames:
    - "kuma.homelab.cloudbending.dev"
  rules:
    - backendRefs:
        - name: uptime-kuma
          port: 3001
