apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openwebui
spec:
  parentRefs:
    - name: default-gateway
      namespace: kube-system
  hostnames:
    - "lama.homelab.cloudbending.dev"
  rules:
    - backendRefs:
        - name: open-webui
          port: 80
