apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: home-assistant
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: octoprint
            k8s:io.kubernetes.pod.namespace: 3d-printing
    - toCIDR:
        - 192.168.32.1/32 # fritz.box
        - 192.168.35.1/32 # Homematic CCU
        - 192.168.36.1/32 # Denon AVR
        - 192.168.36.2/32 # LG TV
    - toCIDR:
        - 157.249.81.141/32 # api.met.no
        - 104.26.4.238/32 # wheels.home-assistant.io
        - 104.26.5.238/32 # wheels.home-assistant.io
        - 172.67.68.90/32 # wheels.home-assistant.io
  ingress:
    - fromEntities:
        - ingress
