apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: home-assistant
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: octoprint
            k8s:io.kubernetes.pod.namespace: 3d-printing
    - toCIDR:
        - 192.168.32.1/32 # fritz.box
        - 192.168.35.1/32 # Homematic CCU
        - 192.168.36.1/32 # Denon AVR
        - 192.168.36.2/32 # LG TV
    # Multicast DNS
    - toCIDR:
        - 224.0.0.251/32
      toPorts:
        - ports:
            - port: "5353"
              protocol: UDP
    # Simple Service Discovery Protocol
    - toCIDR:
        - 239.255.255.250/32
        - 255.255.255.255/32
      toPorts:
        - ports:
            - port: "1900"
              protocol: UDP
    # HTTPS APIs on the internet
    - toCIDR:
        - 157.249.81.141/32 # api.met.no
        - 104.26.4.238/32 # wheels.home-assistant.io
        - 104.26.5.238/32 # wheels.home-assistant.io
        - 172.67.68.90/32 # wheels.home-assistant.io
        - 151.101.0.223/32 # pypi.org
        - 151.101.64.223/32 # pypi.org
        - 151.101.128.223/32 # pypi.org
        - 151.101.192.223/32 # pypi.org
        - 185.85.0.173/32 # warnung.bund.de
        - 185.85.1.149/32 # warnung.bund.de
        - 80.90.16.184/32 # warnung.bund.de
        - 80.90.16.153/32 # warnung.bund.de
        - 185.85.0.244/32 # warnung.bund.de
        - 185.85.0.132/32 # warnung.bund.de
        - 172.67.70.177/32 # ?
        - 172.67.68.101/32 # ?
        - 104.26.6.112/32 # ?
        - 104.26.7.112/32 # ?
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  ingress:
    - fromEntities:
        - ingress
