apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: home-assistant
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
    - toCIDR:
        - 192.168.32.1/32 # fritz.box
        - 192.168.35.1/32 # Homematic CCU
        - 192.168.36.1/32 # Denon AVR
        - 192.168.36.2/32 # LG TV
  ingress:
    - fromEntities:
        - ingress
