apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: homelab
  namespace: fleet-local
  annotations:
    helm.sh/resource-policy: keep
spec:
  repo: "https://github.com/webD97/homelab-cluster-gitops"
  branch: main
  pollingInterval: 300s
  paths:
    - cattle-fleet-system/fleet-crd
    - cattle-fleet-system/fleet

    - kube-system/gateway-api
    - kube-system/cilium
    - kube-system/cilium-preflight
    - kube-system/cilium-l2-config
    - kube-system/cilium-gateway
    - kube-system/cilium-hubble-expose
    - kube-system/sealed-secrets
    - kube-system/generic-device-plugin

    - storage-system/democratic-csi-config
    - storage-system/democratic-csi

    - monitoring-system/kube-prometheus-stack
    - monitoring-system/uptime-kuma
    - monitoring-system/uptime-kuma-extras

    - dns-system/pihole
    - dns-system/external-dns
    - dns-system/coredns-etcd
    - dns-system/coredns-lan

    - x509-system/cert-manager
    - x509-system/cert-manager-hetzner-webhook
    - x509-system/cert-manager-issuers
    - x509-system/static-certs

    - renovate/renovate-token
    - renovate/renovate-bot

    - 3d-printing/octoprint
    - 3d-printing/gridfinitycreator
    - 3d-printing/networkpolicy

    - smart-home/home-assistant
    - smart-home/home-assistant-extras
    - smart-home/networkpolicy

    - virtual-office/paperless-ngx
    - virtual-office/paperless-ngx-extras

    - cnpg-system/cnpg
    - cnpg-system/homelab-db

    - multimedia/jellyfin
    - multimedia/jellyfin-extras

    - ansible-system/cluster-playbooks
