apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless-ngx-pgc
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: paperless-ngx-pg
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: cnpg
            k8s:io.kubernetes.pod.namespace: cnpg-system
    - fromEndpoints:
        - matchLabels:
            cnpg.io/cluster: paperless-ngx-pg
            k8s:io.kubernetes.pod.namespace: virtual-office
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
    - toEntities:
        - kube-apiserver
