apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless-ngx
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: paperless-ngx
  ingress:
    - fromEntities:
        - ingress
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: paperless-ngx-pg
            k8s:io.kubernetes.pod.namespace: virtual-office
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: homelab-virtual-office-paperless-ngx-valkey
            app.kubernetes.io/name: valkey
    - toFQDNs:
        - matchName: posteo.de
      toPorts:
        - ports:
            - port: "993" # IMAP-SSL
              protocol: TCP
    # Update checker
    - toFQDNs:
        - matchName: api.github.com
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
          rules:
            http:
              - method: GET
                path: /repos/paperless-ngx/paperless-ngx/releases/latest
