apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
spec:
  parentRefs:
    - name: default-gateway
      namespace: kube-system
  hostnames:
    - "jellyfin.homelab.cloudbending.dev"
  rules:
    - backendRefs:
        - name: jellyfin
          port: 8096
