apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: paperless
spec:
  parentRefs:
    - name: default-gateway
      namespace: kube-system
  hostnames:
    - "paperless.homelab.cloudbending.dev"
  rules:
    - backendRefs:
        - name: homelab-virtual-office-paperless-ngx
          port: 8000
