---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-virtual-office-paperless-ngx-secret
  namespace: virtual-office
spec:
  encryptedData:
    secret-key: AgBRiLj9pM632Jy+gVQc8T2mbbAcrPLsmf/6ShW3HdvEkxjfZZBytuZw9WkV5oQndnouokLzc4779XxP1Q34PlA4SlGmLKFqTE0sjEgXBK4LdSyTmj1ajV6tHy9iiaqdPvhGgMCyAKKFdGOARSMP1GSEqgwx9kSKdMNma9kb0ZDMN4q1v5wu+5JNF8DRsFThtK01vnQvO9V9ndE75LdQmRdesSkn7Ot4qfbksR0nx+rtGopjQQgUfAgt3pPUvFdhdqOvmyGHaAhKE4aUKTWjPwiG2PGVU2xG5R2/kq0SI8b1dSlIBpWP4qNZNShMpWG8zqyvuZYviZs8CbvtiX59dZOv7yMnWLa/1EctarBQrCS2WoPPglqlmVc9QnFICrG3hSIA7WaNKletkovxwnKA1YLr7UizSGz/talwR9cEMfJGtp8kce8TNVm8di+au+qNJERiNBCZ9laqKtQz6ii88fU4x2Yyg+D2gwDTfdHmN+WwNY2iTDnyqZ/aZbu+pas/5Zfdx0zWyBR7giMPkZxPeQsHu7347NjQznZSW9VUXvGK9zyBaxED5wM5t+MBnKlsKh8fqt+yl5ikcHp7K3jbZyyYFJ1Y7eOhFJKj05YabHc8wCICrvLFHHx7pd44OBhCCSU4Vr6LK5EOLPUEs6Vuhhghpw/8tOPphNBAjQXM5vnoPt5uJl+eM3EZsFbN/NVya7Pzjb80mcKlGgc3yY0bCl3iwwfqEZnbYaPXKT8WV+4SyU2eZuSNd4P10d8qLQX431WrN+M6GIUDqbzgPh49i1WVGPxh2Djytt8cLLGlfWApvRADerj0zw==
  template:
    metadata:
      name: homelab-virtual-office-paperless-ngx-secret
      namespace: virtual-office
