apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: virtual-office
spec:
  encryptedData:
    postgres-password: AgCSqkSa/tUppX7j7flWeJNwxA5TJC5x/yIy/RP8GlVphKtFtuBJ1pdlYlk36pcSJXzN6ZuItbYNeTO4lIXyIFNruQuJ1ckeWXii1gp1EeJSonplQvYt/N1Xljt4Y9Z8eYp6v05V+X43nTtqff44GgH1mRQMSTcXmQWfU/wV/A11NhNyBvxsaVpIhCwZR/eOF6AwP7H5kninzgSf1GDr6UFOMvCUQd6puJrfrfNf/SrwULhnTV9TWmY6zelpsIdzrlvYkXouBVdPn0PBkOTs1mxg+QF8sKnKROeZbGEkggXdhaKYitTWqrthLRAVJGlY4MpiCC5gOHjm9kCyAoYqi58/DO65TEMwQ9EwyAe2eTgzIIIXmPnqoUXn1WhAlMxSJpfi/ZCQb9qBu7GLxmEptMsEUZvUCUVTn2aLTkoz+Lo9dLnZkHA+QseLjH3tRjirKmwh5FhTOzZ3WTIeWcwBWNHzflHXxJ7uPDVjdC5bsaJs3ChMaSOzvZ6Y1XCZgwo4o896M24g6Ulgm7/r607Cjqb83RJCv45d6NfD2C10xho1haXmOX0BvR0TF5XW/UveO+NrKPZSwx5m9SgIvJjnGVvjQF7uMuicpqnoDFgdJrXPXDgLjW3kLuYbFtIQEggr2LJkIAMZZhm8Cc980N2OrhDbPZq8qHeq9bdbdd8jZ5odiwBNdv2CveHfENs6HbUQ4abL6b6Vncq5zgARPR4ShuPE977UcdT/2op/oO/wI1hed4Ngc8luiN/6e/iDDyTc6qY=
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: virtual-office
