defaultNamespace: monitoring-system

dependsOn:
  - selector:
      matchLabels:
        gateway-api-crds: "true"

helm:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 72.5.1
  releaseName: kube-prometheus-stack
  values:
    prometheus:
      prometheusSpec:
        retention: 30d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
    prometheus-node-exporter:
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          effect: NoExecute
          operator: Exists
    extraManifests:
      - apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: prometheus
        spec:
          parentRefs:
            - name: default-gateway
              namespace: kube-system
          hostnames:
            - "prometheus.homelab.cloudbending.dev"
          rules:
            - backendRefs:
                - name: kube-prometheus-stack-prometheus
                  port: 9090
      - apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: grafana
        spec:
          parentRefs:
            - name: default-gateway
              namespace: kube-system
          hostnames:
            - "grafana.homelab.cloudbending.dev"
          rules:
            - backendRefs:
                - name: kube-prometheus-stack-grafana
                  port: 80
