apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: democratic-csi
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: democratic-csi
      app.kubernetes.io/csi-role: controller
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
    - toCIDR:
        - 192.168.37.2/32
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
        - ports:
            - port: "22"
              protocol: TCP
