apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: zot
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: zot
      app.kubernetes.io/name: zot
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: "ghcr.io"
        - matchName: "pkg-containers.githubusercontent.com "
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  ingress:
    - fromEntities:
        - ingress
