# echo -n 'api-token' | kubectl -n x509-system create secret generic hetzner-webhook --dry-run=client --from-file=api-key=/dev/stdin -o json > secret.json
# kubeseal --controller-namespace kube-system --controller-name sealed-secrets -f secret.json -w sealed.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-webhook
  namespace: x509-system
spec:
  encryptedData:
    api-key: AgBmquy3l2ZWi2n8f4hw69MjCWnjOZjUsO/v/7evWP01dLpD/xJNUfziK++0zW+eWx42CrPYOu3GCS7KpfeEM+RZX83q5CvCSfxFCZAwdK+nlL90oPW3AwclyrLoWSKU9ld84XsjulNbM126AR3pkxaHLKZPqMOAL/QCm42WLLiKhP+pOtmq79dRsSLTZN007tL4V/eiDqC7c7c7EVFN/Pe7RfsJrDL58jzMTStGjeoON2JXAluI494RyKr86H9+JnWUrI79+3G5d8lchC6NBVSOaXfit7P5mlk5iVxN46/aq/t95U0VNUGMrA0BedZ2lSQBVnG3rJyCREqJ9PP9RZL9XIvV7Y51Guw6wH1wWYpUG4tOX8GEKHQ6jw0IB0cGmbMgPp17K4G7twb0740ezJqPj+TCG019hwHXGsUXUGLCHKKpCqqznw/SxJdBoTrhYUJlA3Frk0i0c1xQDclQMg7F/sMF1jIO0bj2Sp64mFWX3Gp5vJgBI1eaPJrrXVBqdzagWWUuXJ6LSB87Ee2gVUfFLZ0pSTaCJyN6rKUsjpH+NdOyFdDc/MgfC2mkJsncUe085GucFVPboYcCmPGw+cFVfIjpdX+mI6+o+TDedwOW8CgZrwLZQupGnK+wVkiFFGwaOoLtcxkMqmG/4maGVp0jy6eiWpZqyr+8kaiwRLTXUUtJ9Cn8pnmsdAZx6ZYFbCtd7U4CdrEdQa0=
  template:
    metadata:
      creationTimestamp: null
      name: hetzner-webhook
      namespace: x509-system
