apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lan-announcements
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
      - key: kubernetes.io/hostname
        operator: In
        values:
        - homelab-worker-1
  interfaces:
  - ^enp+
  externalIPs: false
  loadBalancerIPs: true
