apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-staging
spec:
  commonName: "*.homelab.cloudbending.dev"
  dnsNames:
    - "*.homelab.cloudbending.dev"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: letsencrypt-staging
