apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homematic-ccu
spec:
  commonName: "ccu.home.cloudbending.dev"
  dnsNames:
    - "ccu.home.cloudbending.dev"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: homematic-ccu
