apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pve
spec:
  commonName: "pve.home.cloudbending.dev"
  dnsNames:
    - "pve.home.cloudbending.dev"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: pve
  
