apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas
spec:
  commonName: "truenas.home.cloudbending.dev"
  dnsNames:
    - "truenas.home.cloudbending.dev"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: truenas
