apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: carsshad.dhnictead+letsencrypt@posteo.net
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            groupName: acme.cloudbending.dev
            solverName: hetzner
            config:
              secretName: hetzner-webhook
              zoneName: cloudbending.dev
              apiUrl: https://dns.hetzner.com/api/v1
