---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner
  namespace: x509-system
spec:
  encryptedData:
    token: AgAeJPAmEU/oaGNiVnOl2btYIkhC3dqPBxtaVtvtbx20kdfH5tgrhhE8973UkZgKG1EGVglmbP0+fd6NYW83XwsL/nHZ8LAuyAlywJfcFigXL2CRstD7hCqW5JbOMkcQWxlqkVGnBnTpWNpmLCAFXadG5FNflzmNTt1sg5K2983yhpfrxsetPxaJEFskrqptBA3slmPAZkZtsCObTrBANE665wK82u9u7t1pvQPx1YSct8rsAaEjDqV4/3JPe7Z9GHCERXRUG2a+tdyupnAP2hJQ1aG9AiX6jOlnGo5+lbXwAGEZS4IS2ovkeBsUyy6x6KzUfTBNXi1dUr0LTDLuaBj/3USYdhkaGTxO5WVlLH+2ggH7lWqRBX/1lYXCbzUegB0NI0FARWoZZBS3W/U/o/HEPRPz2XgSPHK60A0Gokrvb7pmlUBSwlqoKAvG6XsVDXTdb1MEak0RZ+MjHUnClrLFBLv7ks8B0Klb/BcVh0yiDxNilow90eiYW0Elhhho8OPadlODc8oX8v7iRGq7V042cQNGGOBzCxvPVFtVSGaz0aeCyJGdLC4SV/TfeqA/YaFsjJfx6k/cAva2HqjASuPazMLZ/WkFzEeIpmBSGbyya+XcFk2y+pf6p9EnLpwXdHHx8f59ukOzCKLTR2ILUROqouGQvdWTcaIxLJqWDLQPyOmEb2NzkYSxkIzFiRES0YpLVDqyFKHHK3nUdkm8mWx5bdsGUO2m8+pUJ+mbSeFQp+NHKmrLAUzkKbHSDBMlWKZ7alY9lIq/iowJO5MJj3FS
  template:
    metadata:
      name: hetzner
      namespace: x509-system
