# echo -n 'api-token' | kubectl -n x509-system create secret generic hetzner-webhook --dry-run=client --from-file=api-key=/dev/stdin -o json > secret.json
# kubeseal --controller-namespace kube-system --controller-name sealed-secrets -f secret.json -w sealed.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-webhook
  namespace: x509-system
spec:
  encryptedData:
    api-key: AgAypA7RIZC0VcGY07mjgtZ71qOZfp6FP8Z5u9SIuivDtlH83j19/vnohjxD2gQqbcetl4oLnAnffpA2GwjpxmGGtolIM6nI6nyR/V/W5s2S9Pk0hVkXUnu6yIBkaLfXL3xfgAcTxbcN8WtUw2isJti7lBoTlVudllIpIbTo+nByTGd5VKDkXWJqYK+Syj8E/6HpJsDcRH4coMlW31RukHL7iWvb6lj5aZ8crwiJqttFts4WVYXxLwyf6kdOEzJ4j2DeE550cgBxYMcTusBZVdALAXOyoXFDRH+h0REI7OVIrMR8FFmLO0eF0sfiD4Rzew9jJw0NAhWqzlOeqZRjKr5eqd9CjOxkogJWEBYv0aqk2o2JV7AXqK2BWSO1I12MTk1Pbmoin94IZmSy4HAIv2lSKWoGJNzmaiYoNl1QG6pVLIbCNBmvFM7YxH6z4DlzwOo5fJmiDXNkiPoGxg35Lif/KI1TE/fnuqpjeXKn3WzXd48s7TJgDkk4YbswPH0ywkwz7O2O31p8U20hDeD++jdb9la4cRVUFl6L6lDLLn1eIdyiqaOPYCyFVzSpQZW50GTegie+uXdxcV9ROk11hwfFeP7MNlU4/jF6H2jMjaC9vDF+IbNGLtWvCO8vs/jMtzhwa6Ti1czoL+tw6ceLgNYqj9gcj1HEghuLE3kR55mcy4yfkGFxPf3m2bNfEmupYwtkZSrSgiGvBpHrIBfceEc/wtKTLHQ1RUjXNJ3yZcKN4Q==
  template:
    metadata:
      creationTimestamp: null
      name: hetzner-webhook
      namespace: x509-system
