image:
  repository: docker.io/jellyfin/jellyfin
  tag: "10.11.8"

persistence:
  media:
    size: 2560Gi
  cache:
    type: pvc
    size: 10Gi

resources:
  requests:
    generic.dev/render: 1
  limits:
    generic.dev/render: 1

deploymentStrategy:
  type: Recreate

httpRoute:
  enabled: true
  parentRefs:
    - name: default-gateway
      namespace: kube-system
  hostnames:
    - "jellyfin.homelab.cloudbending.dev"
